### ISSUE TITLE
Getting 10-K for a company returns empty String

### ISSUE THREAD

**Issue by victor4shen** [joeyism/py-edgar#11]
`company = edgar.Company("AARON'S INC", "706688")
a = company.get_10K()
text = edgar.TXTML.parse_full_10K(a)
print(text)`

This code for accessing an Aaron's Inc 10-K gives an empty String. This code works correctly for other companies but fails and returns an empty String for Aaron's Inc. What is the issue here and how can I fix it? I am using the latest version.

**Comment by joeyism** [comment]
Download the newer version. I just pushed a bugfix
