### ISSUE TITLE
TypeError when trying to get CIK from company name.

### ISSUE THREAD

**Issue by Jurga14** [joeyism/py-edgar#12]
Hello, when I try to input a company name into get_cik_by_company_name() it throws a TypeError. Any clue why its doing this?

Thanks 
![TypeError](https://user-images.githubusercontent.com/64226739/85211125-ee2e8c80-b313-11ea-8330-e76b16a29a0a.png)

**Comment by joeyism** [comment]
It couldn't find that company. You have to do exact, with punctuation and everything
