### ISSUE TITLE
get_documents does not return string of content, returns ELEMENT HTML instead

### ISSUE THREAD

**Issue by joezein** [joeyism/py-edgar#13]
Hi,

In the documentation it mentions this should return the content. However I've been getting html elements. Please see attached. 

How do we fix that?

![Screen Shot 2020-06-25 at 11 00 23 AM](https://user-images.githubusercontent.com/58489838/85744673-1252ea80-b6d3-11ea-96a0-cf7b91db43f9.png)

I need the content in strings.

**Comment by joeyism** [comment]
Yea that's on purpose. If you want the text, take each `Element` and run `elem.text_content()`
