### ISSUE TITLE
Having trouble with getting 8-K

### ISSUE THREAD

**Issue by Deanc419** [joeyism/py-edgar#15]
I tried to use the very first sample code and it only returns the html element, not the actual document, When I use the second sample code I am able to get the document. I want to use the first sample code for 8-K's but cannot parse the html, is there a way I can do this; is there some sort of "get_8-K" function. I tried using the "TXTML.get_HTML_from_document" to parse the 8k, but I get a list index out of range error if the number of documents is set to one, if it is more than one I get list object has no attribute tag. Is this the right function that I am using. Thanks (sorry if this is a noob question)

**Comment by joeyism** [comment]
the HTML element is a parsed version of the document. If you want just the text, you can run `.text_content()` to get the text. If you want the raw HTML, you can use `TXTML.to_xml`. Let me know if you need any help

**Comment by Deanc419** [comment]
Thank you; this ended up working well. My only other question is if there is a way I can specify a specific date to get the file after. I noticed you had "prior_to" as a parameter for some of the other functions. Is it possible to have something like an "after" parameter that would return the first 10K after a specific date. Also I was able to create a function based of the the get 10_k function from your source code. It functions the same except it that works for any file type by taking file type as a parameter; therefore making it a little more robust. It looks like your library has a similar function  "get_documents", but it doesn't seem to work for me and returns some weird slashes. Here is the function if you are interested in adding it. Thanks for all the help.

def get_document(company,doc_type):
      BASE_URL = "https://www.sec.gov"
      tree = company.get_all_filings(filing_type=doc_type)
      elems = tree.xpath('//*[@id="documentsbutton"]')[:1]
      result = []
      for elem in elems:
          url = BASE_URL + elem.attrib["href"]
          content_page = Company.get_request(url)
          table = content_page.find_class("tableFile")[0]
          last_row = table.getchildren()[-1]
          href = last_row.getchildren()[2].getchildren()[0].attrib["href"]
          href = BASE_URL + href
          doc = Company.get_request(href)
          result.append(doc)
      return result[0]

**Comment by joeyism** [comment]
Unfortunately, right now there's no support for `after` parameter. If you want, you can add that in a submit a MR. Since you did the work for `get_document`, you could submit a MR for that too.

**Comment by Deanc419** [comment]
Ok thanks. I decided to build my own function that uses beautiful soup and selenium and has date parameters. Once it’s all polished I might add it

**Comment by joeyism** [comment]
yea, feel free to submit a MR. I'm going to close this thread for now then
