### ISSUE TITLE
Issues with parsing 10K filings

### ISSUE THREAD

**Issue by gregjasonroberts** [joeyism/py-edgar#16]
I've tried this on several companies and despite pulling 5 documents, the first element [0] returns a 'list index out of range' error.
I'm using TXTML.parse_full_10K(), which works for the subsequent 4 elements but never for the first.  Is there a different method for the first element I should be using?  I'm working with version 5.3.4.   Thanks!

```python
from edgar import Company
from edgar import TXTML

company = Company("Oracle Corp", "0001341439")
#company = Company("Amazon Com Inc", "0001018724")   
#company = Company('AbbVie Inc.','0001551152')
#company = Company('Alphabet Inc.', '0001652044')

tree = company.get_all_filings(filing_type = "10-K")
docs = Company.get_documents(tree, no_of_documents=5)

text=TXTML.parse_full_10K(docs[0])
text
```

**Comment by joeyism** [comment]
Try it with version [5.3.8](https://github.com/joeyism/py-edgar/releases/tag/5.3.8). I just released a bug fix
