### ISSUE TITLE
Edgar class init fails

### ISSUE THREAD

**Issue by ipl31** [joeyism/py-edgar#2]
Looks like the CIK file the class downloads from SEC/EDGAR now 404s. 
Repro:
`>>> Edgar()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "edgar/edgar.py", line 31, in __init__
    all_companies_array[i] = (item_arr[0], item_arr[1])
IndexError: list index out of range`

Do you plan on continuing to maintain and use this library? I might have some time to try a fix for this but would prefer to avoid it if the library is abandoned. I suspect you will need to migrate to doing CIK lookups on demand instead of pre-caching them since it looks like the SEC no longer has that file available for download.

**Comment by joeyism** [comment]
I do plan on maintaining this library. I'll have to look into this, but if you have time to fix it, I'll definitely look at the merge request

**Comment by joeyism** [comment]
I updated it using https://www.sec.gov/Archives/edgar/cik-lookup-data.txt instead of the old https://www.sec.gov/edgar/NYU/cik.coleft.c

I don't know where to find an updated CIK list, tbh. This is added in v1.0.0

**Comment by ipl31** [comment]
Cool. Thanks I will confirm and close the bug.
  
edit: It works for me.
