### ISSUE TITLE
Issue with match_company_by_company_name

### ISSUE THREAD

**Issue by bosanipietro** [joeyism/py-edgar#22]
Thank you for the amazing library that you have developed and shared!

I am currently trying to find matching company names in the SEC EDGAR database, given that I have a file where the names are not exact matches of their real ones. I have been trying to write the execute the following code: 

`edgar.Edgar.match_company_by_company_name("Neoforma.com Inc")`

but get the following error: 

`match_company_by_company_name() missing 1 required positional argument: 'name'`

I believe the first argument is the self in the Python class, an issue I don't know how to overcome. 
Any help would be greatly appreciated!

**Comment by joeyism** [comment]
Ah, you have to create the `Edgar` object first.
```python
from edgar import Edgar
edgar = Edgar()
edgar.match_company_by_company_name("Neoforma")
```
