### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by rpocase** [joeyism/py-edgar#27]
There have been quite a few commits to master since the last release. It would be nice to get an official pypi release to avoid having to set a commit as a dependency to pull the latest changes.

**Comment by eabase** [comment]
It's even more weird that the official pypi version is 5.4.1, whereas here it is only shown as `5.0.0`.
* https://pypi.org/project/edgar/

What's going on?

**Comment by joeyism** [comment]
It should be released [5.4.3](https://github.com/joeyism/py-edgar/releases/tag/5.4.3)
