### ISSUE TITLE
How do you download these files?

### ISSUE THREAD

**Issue by gstone4242** [joeyism/py-edgar#3]
The code runs great but I am not sure where it is downloading the info im pulling for the company.

**Comment by njdevengine** [comment]
the text is in the array docs:
company = edgar.Company("Oracle Corp", "0001341439")
tree = company.getAllFilings(filingType = "10-K")
docs = edgar.getDocuments(tree, noOfDocuments=5)

you can print(docs) in python, or write a script that outputs it to a text file.
