### ISSUE TITLE
get_documents does not work

### ISSUE THREAD

**Issue by auggunner** [joeyism/py-edgar#6]
I tried the three examples on https://pypi.org/project/edgar/

There is, however, one example that does not work:

from edgar import Company
company = Company("Oracle Corp", "0001341439")
tree = company.get_all_filings(filing_type = "10-K")
docs = edgar.get_documents(tree, no_of_documents=5)

AttributeError: 'Edgar' object has no attribute 'get_documents'

**Comment by joeyism** [comment]
Whoops, in the new version you'll have to import `get_documents` like so:
```python
from edgar.company import get_documents
```
i was thinking of changing that though, so if you have suggestions i'll take it

**Comment by atbe** [comment]
We should update the `README.md` to reflect this change. I'll submit a PR.

**Comment by joeyism** [comment]
@atbe submit a PR and i'll approve it

**Comment by joeyism** [comment]
Updated as of `5.0.0`
