### ISSUE TITLE
Unable to Retrieve Most Updated 10-Q

### ISSUE THREAD

**Issue by sagarsea** [joeyism/py-edgar#8]
`company = Company('COSTCO WHOLESALE CORP.', "909832")
tree = company.get_all_filings(filing_type="10-Q")
docs = get_documents(tree, no_of_documents=5)

texter = tostring(docs[1])
soup=BeautifulSoup(texter,'html.parser')
print(soup.get_text())
`
On executing the above the 10-Q available is for quarterly period ended May 12,2019, while the most current/updated 10-Q available at Edgar for this company is for quarterly period ended November 24,2019
Checked with a couple of other companies as well and last 2-3 10-Qs filed are not available.

**Comment by joeyism** [comment]
I updated a new version (`5.0.0`) with `debug` option, such that
```
get_documents(tree, no_of_documents=5, debug=True)
```
The first document I got was
```
URL: https://www.sec.gov/Archives/edgar/data/909832/000090983219000033/0000909832-19-000033-index.htm
FORM:               
                   
         Filing Date
         2019-12-23                                                                                  
         Accepted        
         2019-12-20 18:04:39
         Documents  
         63        
                         
                                                                                                     
         Period of Report
         2019-11-24
                    
                   
```

I think from your code,
```
texter = tostring(docs[1])
```
should be
```
texter = tostring(docs[0])
```
if you want the first document
